### ISSUE TITLE
This is completely broken

### ISSUE THREAD

**Issue by kargaroc** [lucaswerkmeister/hide-twitter-trends#2]
The trends window on the right side of the screen still appears.
I assume it used to work, but Twitter broke things.

**Comment by lucaswerkmeister** [comment]
It still (mostly) works for me. I can think of some possibilities, but I’ll need some details from you:

- There’s a different (third) version of the trends widget that the extension isn’t aware of yet.
- You have the second version (no cogwheel) and none of your trends have a “trending with” link (see [comment](https://github.com/lucaswerkmeister/hide-twitter-trends/blob/bd4b73785e71689d85930f5137ca2a0df5bd0bf5/hide-twitter-trends.js#L16-L20)).
- You left the Twitter tab open for a while without navigation, and Twitter restored the widget after it was removed. (This happens for me after a few hours or so.) Try going to e.g. your messages and then back.

Can you share a screenshot of what the trends widget looks like on your end?

**Comment by lucaswerkmeister** [comment]
Version 0.5 includes support for another version of the Trends widget (which Twitter started showing to me). I’m going to guess that this is the same version that you got, and close this issue; feel free to reopen if it still doesn’t work for you.
