### ISSUE TITLE
Appears to be non-functional, twitter changed something?

### ISSUE THREAD

**Issue by SleepyAnubis** [lucaswerkmeister/hide-twitter-trends#4]
Extension was working until today (06/04/2023) but appears to no longer be able to hide the trends bar.  Had noticed increased jumpiness for a while as twitter tried to load the element before it was successfully hidden but now it's just staying up.

Firefox 111.0.1 extension version 0.5

**Comment by lucaswerkmeister** [comment]
It’s working for me at the moment, though it’s also sometimes possible that the extension can’t remove the trends in general.
